/*
 * Vantage
 * Vantage API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The Cost model module.
 * @module Vantage/model/Cost
 * @version 1.0.0
 */
export class Cost {
  /**
   * Constructs a new <code>Cost</code>.
   * @alias module:Vantage/model/Cost
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Cost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Vantage/model/Cost} obj Optional instance to populate.
   * @return {module:Vantage/model/Cost} The populated <code>Cost</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Cost();
      if (data.hasOwnProperty('accrued_at'))
        obj.accruedAt = ApiClient.convertToType(data['accrued_at'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('provider'))
        obj.provider = ApiClient.convertToType(data['provider'], 'String');
      if (data.hasOwnProperty('service'))
        obj.service = ApiClient.convertToType(data['service'], 'String');
    }
    return obj;
  }
}

/**
 * The date the cost was accrued. ISO 8601 Formatted - 2021-07-15 or 2021-07-15T19:20:48+00:00.
 * @member {String} accruedAt
 */
Cost.prototype.accruedAt = undefined;

/**
 * The amount of the cost.
 * @member {String} amount
 */
Cost.prototype.amount = undefined;

/**
 * The service provider where the cost was incurred. e.g. AWS
 * @member {String} provider
 */
Cost.prototype.provider = undefined;

/**
 * The service which incurred the cost. e.g. Amazon ElastiCache
 * @member {String} service
 */
Cost.prototype.service = undefined;


