/*
 * Vantage
 * Vantage API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Price} from './Price';

/**
 * The Prices model module.
 * @module Vantage/model/Prices
 * @version 1.0.0
 */
export class Prices {
  /**
   * Constructs a new <code>Prices</code>.
   * Prices model
   * @alias module:Vantage/model/Prices
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Prices</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Vantage/model/Prices} obj Optional instance to populate.
   * @return {module:Vantage/model/Prices} The populated <code>Prices</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Prices();
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], Object);
      if (data.hasOwnProperty('prices'))
        obj.prices = ApiClient.convertToType(data['prices'], [Price]);
    }
    return obj;
  }
}

/**
 * @member {Object} links
 */
Prices.prototype.links = undefined;

/**
 * @member {Array.<module:Vantage/model/Price>} prices
 */
Prices.prototype.prices = undefined;


