/*
 * Vantage
 * Vantage API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Product} from './Product';

/**
 * The Products model module.
 * @module Vantage/model/Products
 * @version 1.0.0
 */
export class Products {
  /**
   * Constructs a new <code>Products</code>.
   * Products model
   * @alias module:Vantage/model/Products
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Products</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Vantage/model/Products} obj Optional instance to populate.
   * @return {module:Vantage/model/Products} The populated <code>Products</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Products();
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], Object);
      if (data.hasOwnProperty('products'))
        obj.products = ApiClient.convertToType(data['products'], [Product]);
    }
    return obj;
  }
}

/**
 * @member {Object} links
 */
Products.prototype.links = undefined;

/**
 * @member {Array.<module:Vantage/model/Product>} products
 */
Products.prototype.products = undefined;


