/*
 * Vantage
 * Vantage API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The Provider model module.
 * @module Vantage/model/Provider
 * @version 1.0.0
 */
export class Provider {
  /**
   * Constructs a new <code>Provider</code>.
   * @alias module:Vantage/model/Provider
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Provider</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Vantage/model/Provider} obj Optional instance to populate.
   * @return {module:Vantage/model/Provider} The populated <code>Provider</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Provider();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Provider.prototype.id = undefined;

/**
 * The common name of the provider.
 * @member {String} name
 */
Provider.prototype.name = undefined;

/**
 * The full descriptive name of the provider.
 * @member {String} description
 */
Provider.prototype.description = undefined;


