/*
 * Vantage
 * Vantage API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Report} from './Report';

/**
 * The Reports model module.
 * @module Vantage/model/Reports
 * @version 1.0.0
 */
export class Reports {
  /**
   * Constructs a new <code>Reports</code>.
   * Reports model
   * @alias module:Vantage/model/Reports
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Reports</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Vantage/model/Reports} obj Optional instance to populate.
   * @return {module:Vantage/model/Reports} The populated <code>Reports</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Reports();
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], Object);
      if (data.hasOwnProperty('reports'))
        obj.reports = ApiClient.convertToType(data['reports'], [Report]);
    }
    return obj;
  }
}

/**
 * @member {Object} links
 */
Reports.prototype.links = undefined;

/**
 * @member {Array.<module:Vantage/model/Report>} reports
 */
Reports.prototype.reports = undefined;


