/*
 * Vantage
 * Vantage API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The Service model module.
 * @module Vantage/model/Service
 * @version 1.0.0
 */
export class Service {
  /**
   * Constructs a new <code>Service</code>.
   * @alias module:Vantage/model/Service
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Service</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Vantage/model/Service} obj Optional instance to populate.
   * @return {module:Vantage/model/Service} The populated <code>Service</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Service();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Service.prototype.id = undefined;

/**
 * The type of cloud service.
 * @member {String} category
 */
Service.prototype.category = undefined;

/**
 * The common name of the service. Usually an abbreviation.
 * @member {String} name
 */
Service.prototype.name = undefined;

/**
 * The full name of the service.
 * @member {String} description
 */
Service.prototype.description = undefined;


