/*
 * Vantage
 * Vantage API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from './ApiClient.js';
import {Price} from './model/Price.js';
import {Prices} from './model/Prices.js';
import {Product} from './model/Product.js';
import {Products} from './model/Products.js';
import {Provider} from './model/Provider.js';
import {Providers} from './model/Providers.js';
import {Service} from './model/Service.js';
import {Services} from './model/Services.js';
import {PingApi} from './Vantage/PingApi.js';
import {PricesApi} from './Vantage/PricesApi.js';


/**
* Vantage API Client.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Vantage = require('Vantage/index'); // See note below*.
* var xxxSvc = new Vantage.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Vantage.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['Vantage/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Vantage.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Vantage.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module Vantage/index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:Vantage/ApiClient}
     */
    ApiClient,

    /**
     * The Price model constructor.
     * @property {module:Vantage/model/Price}
     */
    Price,

    /**
     * The Prices model constructor.
     * @property {module:Vantage/model/Prices}
     */
    Prices,

    /**
     * The Product model constructor.
     * @property {module:Vantage/model/Product}
     */
    Product,

    /**
     * The Products model constructor.
     * @property {module:Vantage/model/Products}
     */
    Products,

    /**
     * The Provider model constructor.
     * @property {module:Vantage/model/Provider}
     */
    Provider,

    /**
     * The Providers model constructor.
     * @property {module:Vantage/model/Providers}
     */
    Providers,

    /**
     * The Service model constructor.
     * @property {module:Vantage/model/Service}
     */
    Service,

    /**
     * The Services model constructor.
     * @property {module:Vantage/model/Services}
     */
    Services,

    /**
    * The PingApi service constructor.
    * @property {module:Vantage/Vantage/PingApi}
    */
    PingApi,

    /**
    * The PricesApi service constructor.
    * @property {module:Vantage/Vantage/PricesApi}
    */
    PricesApi
};
